version: "3.8"

services:
  app:
    build: .
    environment:
      - BUNDLE_PATH=/bundle/vendor
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    stdin_open: true
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}

volumes:
  bundle:
  db_data:
