default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>
  host: <%= ENV['HOST_DB'] %>
  port:  <%= ENV['PORT_DB'] %>

development:
  <<: *default
  database: intern_db

test:
  <<: *default
  database: test_intern_db

production:
  <<: *default
  database: production_intern_db
